version: '3'

services:
  mongo_db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_db:/data/db

  backend:
    build: ./backend
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: backend
    volumes:
      - .:/backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
  
volumes:
  mongo_db: 